wazibo-haproxy:
  container_name: wazibo-haproxy
  build: ./wazibo-haproxy
  links:
    - wazibo-web
    - wazibo-server
  ports:
    - "80:80"
wazibo-server:
  container_name: wazibo-server
  build: ./wazibo-server
  ports:
    - "9080"
  volumes:
    - ./wazibo-server:/wazibo-server/src
  links:
    - wazibo-mongo
  environment: 
    - WAZIBO_WEB_URL=localweb.wazibo.com
    - WAZIBO_API_URL=localapi.wazibo.com
    - WAZIBO_HTTP_TRANSPORT=http
  restart: always
wazibo-web:
  container_name: wazibo-web
  build: ./wazibo-web
  ports:
    - "9080"
  volumes:
    - ./wazibo-web:/wazibo-web/src
  links:
    - wazibo-mongo
    - wazibo-server:wazibo-server
  environment: 
    - WAZIBO_WEB_URL=localweb.wazibo.com
    - WAZIBO_API_URL=localapi.wazibo.com
    - WAZIBO_HTTP_TRANSPORT=http
  restart: always
wazibo-mongo:
  container_name: wazibo-mongo
  image: mongo
  ports:
   - "27017:27017"
  volumes:
    - /data/db
  command: --smallfiles --quiet --logpath=/dev/null
