apiVersion: v1
kind: Service
metadata:
  name: wazibo-server
  labels:
    name: wazibo-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9080
      protocol: TCP
  selector:
    name: wazibo-server