apiVersion: v1
kind: Service
metadata:
  name: wazibo-haproxy
  labels:
    name: wazibo-haproxy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: wazibo-haproxy