apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx-ssl-proxy-api
  name: nginx-controller
spec:
  replicas: 1
  selector:
    name: nginx-ssl-proxy-api
  template:
    metadata:
      labels:
        name: nginx-ssl-proxy-api
    spec:
      containers:
        - image: us.gcr.io/wazibo-1143/wazibo-nginx
          imagePullPolicy: Always        
          name: nginx-ssl-proxy-api
          volumeMounts: 
            - name: "secrets"
              mountPath: "/etc/secrets"
              readOnly: true
          env:
            - name: "WEB_SERVICE_HOST_ENV_NAME"
              value: "WAZIBO_WEB_SERVICE_HOST"
            - name: "WEB_SERVICE_PORT_ENV_NAME"
              value: "WAZIBO_WEB_SERVICE_PORT"
            - name: "API_SERVICE_HOST_ENV_NAME"
              value: "WAZIBO_SERVER_SERVICE_HOST"
            - name: "API_SERVICE_PORT_ENV_NAME"
              value: "WAZIBO_SERVER_SERVICE_PORT"
            - name: "ENABLE_SSL"
              value: "true"
            - name: CERT_SERVICE_HOST_ENV_NAME
              value: LETSENCRYPT_SERVICE_SERVICE_HOST
            - name: CERT_SERVICE_PORT_ENV_NAME
              value: LETSENCRYPT_SERVICE_SERVICE_PORT
            - name: WEB_SERVER_NAME
              value: "wazibo.com www.wazibo.com"
            - name: API_SERVER_NAME
              value: "api.wazibo.com"
            - name: CERT_SERVER_NAME
              value: "wazibo.com www.wazibo.com api.wazibo.com"
          ports:
            - name: "sslproxyhttp"
              containerPort: 80
            - name: "sslproxyhttps"
              containerPort: 443
      volumes: 
        - name: "secrets"
          secret: 
            secretName: "certs-wazibo.com"