apiVersion: v1
kind: Service
metadata:
  name: wazibo-nginx
  labels:
    name: nginx-ssl-proxy-api
spec:
  type: LoadBalancer
  ports:
    - name: "https"
      port: 443
      targetPort: "sslproxyhttps"
      protocol: "TCP"
    - name: "http"
      port: 80
      targetPort: "sslproxyhttp"
      protocol: "TCP"
  selector:
    name: nginx-ssl-proxy-api