apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: wazibo-web
  name: web-controller
spec:
  replicas: 1
  selector:
    name: wazibo-web
  template:
    metadata:
      labels:
        name: wazibo-web
    spec:
      containers:
      - image: us.gcr.io/wazibo-1143/wazibo-web:master.8
        imagePullPolicy: Always
        env:
          - name: WAZIBO_WEB_URL
            value: www.wazibo.com
          - name: WAZIBO_API_URL
            value: api.wazibo.com
          - name: WAZIBO_HTTP_TRANSPORT
            value: http
        name: wazibo-web
        ports:
        - containerPort: 9080